<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.2">
    <title>Links for datasette-show-errors</title>
  </head>
  <body>
    <h1>Links for datasette-show-errors</h1>
<a href="https://files.pythonhosted.org/packages/fb/6c/59c5cd375392c0780e46ddbfd81798051d8117170defe0e2087166316f46/datasette_show_errors-0.2-py3-none-any.whl#sha256=cbc9dda3970e01e4b0ac00bb976fe285f4cb649cfe76955bf4d3e3915cf06993" data-dist-info-metadata="sha256=56915c4995eb504550aab361fcf6a7935e0af3bc11f403ea2f1ed7bc36800b42" data-core-metadata="sha256=56915c4995eb504550aab361fcf6a7935e0af3bc11f403ea2f1ed7bc36800b42">datasette_show_errors-0.2-py3-none-any.whl</a><br />
</body>
</html>
<!--SERIAL 6856003-->