<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.1">
    <title>Links for exceptionman</title>
  </head>
  <body>
    <h1>Links for exceptionman</h1>
<a href="https://files.pythonhosted.org/packages/76/6b/57b90a54185f4b3843d43be44702a2879a20a779d57266e286ed8ad313d3/ExceptionMan-0.0.0.dev0-py3-none-any.whl#sha256=9d8ed810b086105891571c49fb57d65c4a4fd0d2610b78d96726caa45a1e4fea" data-requires-python="&gt;=3.10" data-dist-info-metadata="sha256=cb65c487657ad0d0fae1ee577083f088b6f8e9e07f8f1e6d21ec7c473845074d" data-core-metadata="sha256=cb65c487657ad0d0fae1ee577083f088b6f8e9e07f8f1e6d21ec7c473845074d">ExceptionMan-0.0.0.dev0-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/d0/4d/2720183451bd048779b6b954ed996059d5374e2375d4f15811acf8cb8827/exceptionman-0.0.0.dev0.tar.gz#sha256=72ef57d6b1d9c6e0a563485b25c11851b18b586492ebfd64a5e1d393ed6fcb6b" data-requires-python="&gt;=3.10" >exceptionman-0.0.0.dev0.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/44/a4/99b0cc233442f8a0cc03b425d83f9f8461f7f71683f0f0e60782d4422a6d/ExceptionMan-0.0.0.dev1-py3-none-any.whl#sha256=db5bdc89dd4e48647af2c8725414c727b9ff396b0bc745c8b183a993c87559a1" data-requires-python="&gt;=3.10" data-dist-info-metadata="sha256=654e35f1b24b404cd30eb7e341d4fc47535dbf4fd6790bd8ace940ead8c26669" data-core-metadata="sha256=654e35f1b24b404cd30eb7e341d4fc47535dbf4fd6790bd8ace940ead8c26669">ExceptionMan-0.0.0.dev1-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/2e/a1/ddf7cf5a558a02f72c7a764cc2ac5acb78aad6f187cc3f99aa71e0835c62/exceptionman-0.0.0.dev1.tar.gz#sha256=bdf1c6286ccf7a45c5e21fe4275f1cdbffc4a2569a3b490c13bb6dd75e9f68b3" data-requires-python="&gt;=3.10" >exceptionman-0.0.0.dev1.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/a0/2c/0d52948a3fbad912936cc810cd95136f5d29a1e927a5c2d506a52728c364/ExceptionMan-0.0.0.dev2-py3-none-any.whl#sha256=b4ff9bfb2cbb95ca50d478874115be860b145e9f5eb5a60d3e8583628f1220d5" data-requires-python="&gt;=3.10" data-dist-info-metadata="sha256=19cb5de68a2a0df998b859bbf63d76f25816a0c11d0fcd3601887fff78014de5" data-core-metadata="sha256=19cb5de68a2a0df998b859bbf63d76f25816a0c11d0fcd3601887fff78014de5">ExceptionMan-0.0.0.dev2-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/82/b6/cc829997e658dca681107b60eb2ba6367455cb1b3cbe2d2086e57b6b09af/exceptionman-0.0.0.dev2.tar.gz#sha256=275af7015b9fe6ef9df3739911080f9414aaa778a147374b4b5e2acde8481084" data-requires-python="&gt;=3.10" >exceptionman-0.0.0.dev2.tar.gz</a><br />
</body>
</html>
<!--SERIAL 24971008-->